### ISSUE TITLE
Example calling from Objective c

### ISSUE THREAD

**Issue by geogerar** [vladislav-k/VKCheckbox#1]
Hi,

Is it possible to include an example for calling your classes from objective c?
Especially I would like to see how can call from objective c the "checkboxValueChangedBlock".

Thank you in advance

George Gerardis

**Comment by vladislav-k** [comment]
Hi @geogerar,

please see newly added `VKCheckboxExample-ObjC` which will show you how to use `VKCheckbox` class in your Obj-C project.
