### ISSUE TITLE
When used in tableViewCell, check mark goes missing.

### ISSUE THREAD

**Issue by glennposadas** [vladislav-k/VKCheckbox#10]
Any idea?

	import GPKit
	import UIKit

	protocol SelectShiftTableViewCellDelegate: NSObjectProtocol {
	    func selectShiftTableViewCell(isSelectedDidUpdate isSelected: Bool, selectShiftTableViewCell: SelectShiftTableViewCell)
	}

	class SelectShiftTableViewCell: UITableViewCell {
	    
	    // MARK: - Properties
	    
	    @IBOutlet weak var label_Shift: UILabel!
	    @IBOutlet weak var label_Time: UILabel!
	    @IBOutlet weak var label_Day: UILabel!
	    @IBOutlet weak var checkBox: VKCheckbox!
	    
	    weak var delegate: SelectShiftTableViewCellDelegate?
	    
	    var indexPath: IndexPath! {
	        didSet {
	            self.label_Shift.isHidden = self.indexPath.row != 0
	        }
	    }
	    
	    // MARK: - Functions
	    
	    func populateWithData(day: String?, schedule: DummyDataSchedule?, isSelected: Bool = false) {
	        if let day = day,
	            let schedule = schedule {
	            self.label_Day.text = day
	            self.label_Time.text = "\(schedule.timeIn!) in \(schedule.timeOut!)"
	        }
	    }
	    
	    // MARK: Override
	    
	    override func awakeFromNib() {
	        super.awakeFromNib()
	        
	        // Customized checkbox
	        self.checkBox.setupCheckBox(delegate: self, defaultValue: false)
	        self.checkBox.line             = .thin
	        self.checkBox.bgColorSelected  = FindWorkColor.blueLight2EB7FC
	        self.checkBox.bgColor          = .white
	        self.checkBox.color            = .white
	        self.checkBox.borderColor      = FindWorkColor.gray8A8FA5
	        self.checkBox.borderWidth      = 1
	        self.checkBox.cornerRadius     = self.checkBox.frame.size.height / 2
	    }
	    
	    override func setSelected(_ selected: Bool, animated: Bool) {
	        super.setSelected(selected, animated: animated)
	        
	        GPLog(classSender: self, log: "🐸Set Selected")
	        
	        self.checkBox.setOn(selected, animated: animated)
	    }
	}

	// MARK: - VKCheckBoxDelegate

	extension SelectShiftTableViewCell: VKCheckBoxDelegate {
	    func checkbox(stateDidChange isOn: Bool, vkCheckbox: VKCheckbox) {
	        GPLog(classSender: self, log: "🐷stateDidChange")
	        self.delegate?.selectShiftTableViewCell(isSelectedDidUpdate: isOn, selectShiftTableViewCell: self)
	    }
	}

**Comment by vladislav-k** [comment]
Hi @glennposadas ,

For some reason, which is not clear to me, table view's selection affects on checkmark view. But with this I've successfully use this control with table view cell in some of my projects. 

I found another issue with background color when control is being used in the cell. Please pull the update. Also please check out the new Swift Demo app. It shows how VKCheckbox may be used without any issues.

Thanks
