### ISSUE TITLE
Checkmark is out of checkbox bounds

### ISSUE THREAD

**Issue by geogerar** [vladislav-k/VKCheckbox#2]
Hello again,
thanks for the objective c example.
I hate one more notice.
When I create checkbox programmatically and not in IB then the checkmark is out of checkbox bounds.
Can you take a look and fix it.

Thanks again.

George

**Comment by vladislav-k** [comment]
Hi @geogerar,

please provide a code snippet how do you create it.

Thanks

**Comment by geogerar** [comment]
Hi again,

following is the way I create it.....
------------------------------------------------------------------
    // Customized checkbox
    VKCheckbox *checkbox = [[VKCheckbox alloc] init];
    checkbox.frame = CGRectMake(50, 130, 40, 40);
    [checkbox setOn:NO];
    checkbox.borderWidth = 2.0;
    checkbox.borderColor = [UIColor redColor];
    checkbox.cornerRadius = 3.0;
    checkbox.bgColor = [UIColor whiteColor];
    checkbox.bgColorSelected = [UIColor blackColor];
    checkbox.color = [UIColor yellowColor];
    checkbox.line = VKCheckboxLineNormal;
    checkbox.checkboxValueChangedBlock = ^(BOOL state){
        NSLog(@"Custom checkbox is %@", state ? @"ON" : @"OFF");
    };

    [self.view addSubview:checkbox];
----------------------------------------------------------------------

Everything works fine except that checkmark is out of bounds of checkbox (up and left) and that touching checkbox is really hard......

Thanks

George

**Comment by vladislav-k** [comment]
@geogerar,

Issue is fixed within new update. 

Enjoy `VKCheckbox`,
Thanks
