### ISSUE TITLE
clicking on description

### ISSUE THREAD

**Issue by YurchukV** [vladislav-k/VKCheckbox#8]
Add the possibility to by clicking on the description of the checkbox, the checkbox is also breakdowns

**Comment by vladislav-k** [comment]
Hi @YurchukV,

VKCheckbox doesn't include a description feature and works just like UISwitch control. You have to add description UI in a separately from the checkbox. 

Thanks

**Comment by YurchukV** [comment]
it would be convenient if there was such a possibility

**Comment by vladislav-k** [comment]
I suggest you to subclass this control and add any features you want. As I mentioned before, the main idea of this control is be such simple as UISwitch.
